replayBufferSize: 300
batchReplaySize: 32
batch_size: 32
discounted: 0.9
er: true
online_learning: full
patience: 3
seq_len: 96
td: true
timeenc: 2
train_epochs: 10
trainer: w_student.trainerFramework_ERTDRes
use_amp: false
num_ERepochs: 1
freq_ERupdate: 1
td_k: 
  - 1