opt_main:
  test:
    batch:
      amsgrad: true
      lr: 0.0009669458098272828
      opt: adamw
    online:
      amsgrad: true
      lr: 0.0001
      opt: adam
  train:
    amsgrad: true
    lr: 0.008709167923671785
    opt: adam
opt_student:
  test:
    batch:
      amsgrad: true
      lr: 0.0009014283349132542
      opt: adamw
    online:
      amsgrad: true
      lr: 0.00012126179383993894
      opt: adamw
  train:
    amsgrad: true
    lr: 0.0031040059446048353
    opt: adamw
