opt_main:
  test:
    batch:
      amsgrad: true
      lr: 0.0021561102325122644
      opt: adamw
    online:
      amsgrad: true
      lr: 0.0019520515308410907
      opt: adam
  train:
    amsgrad: true
    lr: 0.002498162969146163
    opt: adam
opt_student:
  test:
    batch:
      amsgrad: true
      lr: 0.0021561102325122644
      opt: adamw
    online:
      amsgrad: true
      lr: 0.0019520515308410907
      opt: adamw
  train:
    amsgrad: true
    lr: 0.002498162969146163
    opt: adamw
