trainer: wo_student.trainerFramework_plain
train_epochs: !!int 10 # train epochs
patience: !!int 3 # early stopping patience
use_amp: !!bool false # use automatic mixed precision training
online_learning: !!str full
batch_size: 32
seq_len: 96
timeenc: 2
