opt_main:
  test:
    batch:
      amsgrad: false
      lr: 0.001
      opt: adam
    online:
      amsgrad: false
      lr: 0.001
      opt: adam
  train:
    amsgrad: true
    lr: 0.0014108973807062716
    opt: adam
