opt_main:
  test:
    batch:
      amsgrad: false
      lr: 0.001
      opt: adam
    online:
      amsgrad: false
      lr: 0.001
      opt: adam
  train:
    amsgrad: false
    lr: 0.0026450429737427156
    opt: adamw
