opt_main:
  test:
    batch:
      amsgrad: true
      lr: 0.0007909716513747983
      opt: adamw
    online:
      amsgrad: true
      lr: 0.0001
      opt: adam
  train:
    amsgrad: true
    lr: 0.002928347346310541
    opt: adam
