opt_main:
  test:
    batch:
      amsgrad: true
      lr: 0.0037899050019140393
      opt: adamw
    online:
      amsgrad: true
      lr: 0.002867969832521614
      opt: adam
  train:
    amsgrad: true
    lr: 0.002044002700319083
    opt: adam
opt_student:
  test:
    batch:
      amsgrad: true
      lr: 0.0037899050019140393
      opt: adamw
    online:
      amsgrad: true
      lr: 0.002867969832521614
      opt: adamw
  train:
    amsgrad: true
    lr: 0.002044002700319083
    opt: adamw
