opt_main:
  test:
    batch:
      amsgrad: true
      lr: 0.001
      opt: adamw
    online:
      amsgrad: true
      lr: 0.001
      opt: adam
  train:
    amsgrad: true
    lr: 0.001
    opt: adam
opt_student:
  test:
    batch:
      amsgrad: true
      lr: 0.001
      opt: adamw
    online:
      amsgrad: true
      lr: 0.001
      opt: adamw
  train:
    amsgrad: true
    lr: 0.001
    opt: adamw
