learning_rate_bias: 0.001
learning_rate_w: 0.001
opt_main:
  test:
    batch:
      amsgrad: false
      lr: 0.0007354229393739211
      opt: adamw
    online:
      amsgrad: false
      lr: 0.0012962384174597923
      opt: adamw
  train:
    amsgrad: false
    lr: 0.001105325601038844
    opt: adam
opt_student:
  test:
    batch:
      amsgrad: true
      lr: 0.000489630332305972
      opt: adam
    online:
      amsgrad: false
      lr: 0.00046484694974589547
      opt: adamw
  train:
    amsgrad: true
    lr: 0.006810035209075159
    opt: adam
