learning_rate_bias: 0.001
learning_rate_w: 0.001
opt_main:
  test:
    batch:
      amsgrad: true
      lr: 9.243278015483322e-05
      opt: adamw
    online:
      amsgrad: false
      lr: 0.003321876799917642
      opt: adamw
  train:
    amsgrad: true
    lr: 0.004229976482359455
    opt: adamw
opt_student:
  test:
    batch:
      amsgrad: true
      lr: 0.0008422040106415054
      opt: adam
    online:
      amsgrad: true
      lr: 0.0008957117947391834
      opt: adamw
  train:
    amsgrad: false
    lr: 0.005984505234863916
    opt: adam
