trainer: w_student.trainerFramework_ERTDnonRes
train_epochs: !!int 10 # train epochs
patience: !!int 3 # early stopping patience
use_amp: !!bool false # use automatic mixed precision training
online_learning: !!str full
batch_size: 32
seq_len: 96
timeenc: 2
discounted: 0.9
replayBufferSize: 300
batchReplaySize: 32
td: True
er: true
num_ERepochs: 1
freq_ERupdate: 1
td_k: 
  - 1