opt_main:
  test:
    batch:
      amsgrad: true
      lr: 2.2401331167084008e-05
      opt: adamw
    online:
      amsgrad: true
      lr: 3.265077492010097e-05
      opt: adam
  train:
    amsgrad: true
    lr: 0.003960126234898782
    opt: adam
opt_student:
  test:
    batch:
      amsgrad: true
      lr: 0.0004903967574519644
      opt: adamw
    online:
      amsgrad: true
      lr: 0.0003447404893153253
      opt: adamw
  train:
    amsgrad: true
    lr: 0.003625125739672411
    opt: adamw
