opt_main:
  test:
    batch:
      amsgrad: true
      lr: 0.0007909716513747983
      opt: adamw
    online:
      amsgrad: false
      lr: 0.002867969832521614
      opt: adamw
  train:
    amsgrad: true
    lr: 0.002928347346310541
    opt: adamw
