opt_main:
  test:
    batch:
      amsgrad: false
      lr: 0.001
      opt: adam
    online:
      amsgrad: false
      lr: 0.001
      opt: adam
  train:
    amsgrad: true
    lr: 1.2085692577355387e-05
    opt: adamw
