opt_main:
  test:
    batch:
      amsgrad: true
      lr: 3.43499000213282e-05
      opt: adamw
    online:
      amsgrad: true
      lr: 0.0001
      opt: adam
  train:
    amsgrad: true
    lr: 0.009521474319552392
    opt: adam
